# Generated by Django 4.1 on 2022-09-27 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_description_alter_task_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 15, 38, 58, 767327)),
        ),
    ]
