# Generated by Django 4.1 on 2022-09-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_is_finished_alter_task_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 16, 49, 48, 944655)),
        ),
    ]
